language: python
python:
  - "3.5"
git:
  depth: 3
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unixodbc unixodbc-dev
install: "pip install -r requirements.txt"
script:
  - "pep8 pokerserver && python setup.py lint --lint-rcfile setup.cfg"
  - "python setup.py nosetests"
